simulator: main.o Scheduling.o PQHeap.o Heap.o Request.o
	g++ -o simulator main.o Scheduling.o PQHeap.o Heap.o Request.o

main.o: main.cpp
	g++ -c main.cpp

Scheduling.o: Scheduling.cpp
	g++ -c Scheduling.cpp

PQHeap.o: PQHeap.cpp
	g++ -c PQHeap.cpp

Heap.o: Heap.cpp
	g++ -c Heap.cpp

Request.o: Request.cpp
	g++ -c Request.cpp